<?php

namespace App\Filament\Resources\Cjip\SliderResource\Pages;

use App\Filament\Resources\Cjip\SliderResource;
use Filament\Actions;
use Filament\Actions\LocaleSwitcher;
use Filament\Resources\Pages\CreateRecord;

class CreateSlider extends CreateRecord
{
    use CreateRecord\Concerns\Translatable;
    protected static string $resource = SliderResource::class;

    protected function getHeaderActions(): array
    {
        return [
            LocaleSwitcher::make(),
        ];
    }

    public static function getTranslatableLocales(): array
    {
        return ['id', 'en'];
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        //dd($data);
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
