<?php

namespace App\Filament\Resources\Cjip\BeritaResource\Pages;

use App\Filament\Resources\Cjip\BeritaResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateBerita extends CreateRecord
{
    use CreateRecord\Concerns\Translatable;
    protected static string $resource = BeritaResource::class;

    public static function getTranslatableLocales(): array
    {
        return ['en', 'id'];
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\LocaleSwitcher::make(),
            // ...
        ];
    }


    protected function mutateFormDataBeforeCreate(array $data): array
    {
        //dd($data);
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
