<?php

namespace App\Filament\Resources\Cjip\LoiResource\Pages;

use App\Filament\Resources\Cjip\LoiResource;
use App\Filament\Widgets\LoiBySektor;
use App\Filament\Widgets\LoiByCountry;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Filament\Tables\Actions\Action;

class ListLois extends ListRecords
{
    protected static string $resource = LoiResource::class;

    protected function getHeaderWidgets(): array
    {
        return [
            LoiBySektor::class,
            LoiByCountry::class,
        ];
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    protected function getTableQuery(): Builder
    {

        //dd(auth()->user()->id);

        if (auth()->user()->hasRole('lo')) {
            return parent::getTableQuery()->where('user_lo', auth()->user()->id);
        }

        return parent::getTableQuery(); // TODO: Change the autogenerated stub
    }

    protected function getTableActions(): array
    {
        return array_merge(
            parent::getTableActions(),
            [
                Action::make('print')
                    ->url(fn(Model $record) => url('') . $record->doc_loi)
                    ->openUrlInNewTab()
            ]
        );
    }
}
