<?php

namespace App\Filament\Resources\SiRusa\BapResource\Pages;

use App\Filament\Resources\SiRusa\BapResource;
use App\Models\SiMike\Proyek;
use Carbon\Carbon;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateBap extends CreateRecord
{
    protected static string $resource = BapResource::class;

    public function mount(): void
    {
        $this->form->fill([
            'proyek_id' => request()->query('id_proyek')
        ]);
        // dd($this->form);
        parent::mount(); // TODO: Change the autogenerated stub
    }

    protected function beforeFill(): void
    {
        $this->data['proyek_id'] = request()->query('id_proyek');
    }


    protected function mutateFormDataBeforeCreate(array $data): array
    {

        if ($data['proyek_id']) {
            $record = Proyek::where('id', $data['proyek_id'])->first();
            //dd($record);
            $data['proyek_id'] = $record->id;
            $nama_perusahaan = $record->nibCheck->uraian_jenis_perusahaan . '.' . $record->nibCheck->nama_perusahaan;
            $alamat = $record->alamat;
            $status_perusahaan = $record->nibCheck->status_penanaman_modal;
            $skala_usaha = $record->uraian_skala_usaha;
            $kabkota = $record->kabkota->nama;
            $nama = $data['nama'];
            $jabatan = $data['jabatan'];
            $resiko = $record->uraian_risiko_proyek;
            $nib = $data['nib'];
            //dd($data['tanggal_nib']);
            $tanggal_terbit_nib = Carbon::createFromFormat('Y-m-d', $data['tanggal_nib'])->isoFormat('D MMMM Y');
            $kbli = $record->kbli;
            $deskripsi_kbli = $record->judul_kbli;


            if ($data['is_punya_ss']) {
                $content_ss = "";
                foreach ($data['detail_ss'] as $ss) {
                    $nama_ss = $ss['nama'];
                    $nomor_ss = $ss['ss'];
                    $content_ss .= "
                                    <li>
                                    <p>$nama_perusahaan mempunyai $nama_ss dengan nomor: $nomor_ss;</p>
                                    </li>
                                ";
                }
            } else {
                $content_ss = '';
            }

            $content_listrik = "";
            foreach ($data['sumber_listriks'] as $lstrik) {
                $sumber = $lstrik['sumber'];
                $daya = $lstrik['kapasitas_listrik'];
                $content_listrik .= "
                                    <li>
                                        <p>Kapasitas listrik di lokasi proyek bersumber dari $sumber dengan daya $daya Kva ;</p>
                                    </li>
                                ";
            }
            $current_month = date('n'); // get the current month as a number (1-12)
            $tw = ceil($current_month / 3);
            $tahun = now()->year;
            $keterangan_riil = $data['keterangan_riil'] ?? '';

            $content_tanggal_operasi = "";
            if (array_key_exists('tanggal_mulai_operasi', $data)) {
                $tgl_op = Carbon::createFromFormat('Y-m-d', $data['tanggal_mulai_operasi'])->isoFormat('D MMMM Y');
                $content_tanggal_operasi .= "
                            <li>
                                    <p>$nama_perusahaan mulai berproduksi pada tanggal $tgl_op;</p>
                            </li>
                            ";
            } else {
                $tgl_kon = Carbon::createFromFormat('Y-m-d', $data['tanggal_konstruksi_selesai'])->isoFormat('D MMMM Y');
                $content_tanggal_operasi .= "
                            <li>
                                    <p>Tahap konstruksi $nama_perusahaan diperkirakan akan selesai pada $tgl_kon;</p>
                            </li>
                            ";
            }

            $content_tk = "";
            $sum_tk = array_sum(array_column($data['tk'], 'jumlah_tk'));
            $tk_laki2 = array_reduce(array_filter($data['tk'], function ($item) {
                return $item['jenis_tk'] === 'L';
            }), function ($result, $item) {
                return $item['jumlah_tk'];
            });
            $tk_perempuan = array_reduce(array_filter($data['tk'], function ($item) {
                return $item['jenis_tk'] === 'P';
            }), function ($result, $item) {
                return $item['jumlah_tk'];
            });
            if ($data['tka'] & $data['is_bpjs']) {
                $content_tk .= "
                            <li>
                                    <p>Perusahaan memiliki karyawan $sum_tk orang dengan jumlah laki-laki $tk_laki2 orang dan perempuan $tk_perempuan yang merupakan Tenaga Kerja Indonesia dan memliki Tenaga Kerja Asing sejumlah {$data['tka']}. Perusahaan ini mempunyai jam kerja dengan {$data['jam_kerja']}. Seluruh karyawan sudah terlindungi dengan program BPJS (Kesehatan dan Naker).</p>
                            </li>
                            ";
            } elseif ($data['is_bpjs']) {
                $content_tk .= "
                            <li>
                                    <p>Perusahaan memiliki karyawan $sum_tk orang dengan jumlah laki-laki $tk_laki2 orang dan perempuan $tk_perempuan yang merupakan Tenaga Kerja Indonesia. Perusahaan ini mempunyai jam kerja dengan {$data['jam_kerja']}. Seluruh karyawan sudah terlindungi dengan program BPJS (Kesehatan dan Naker).</p>
                            </li>
                            ";
            } else {
                $content_tk .= "
                            <li>
                                    <p>Perusahaan memiliki karyawan $sum_tk orang dengan jumlah laki-laki $tk_laki2 orang dan perempuan $tk_perempuan yang merupakan Tenaga Kerja Indonesia dan. Perusahaan ini mempunyai jam kerja dengan {$data['jam_kerja']}. Seluruh karyawan belum terlindungi dengan program BPJS (Kesehatan dan Naker).</p>
                            </li>
                            ";
            }

            $content_lapor_lkpm = "";
            if ($data['is_lapor_lkpm']) {
                $content_lapor_lkpm .= "
                                <li>
                                    <p>Pada triwulan $tw tahun $tahun, perusahaan sudah melaporkan LKPM;</p>
                                </li>
                            ";
            } else {
                $content_lapor_lkpm .= "
                                <li>
                                    <p>Perusahaan belum melaporkan LKPM dikarenakan {$data['kendala_lkpm']};</p>
                                </li>
                            ";
            }

            $content_kapasitas = "";
            foreach ($data['jenis_kapasitas_produksi'] as $kapasitas) {
                $jenis = $kapasitas['jenis_kapasitas'];
                $realisasi_kapasitas = $kapasitas['realisasi_kapasitas_produksi'];
                $satuan = $kapasitas['satuan_kapasitas_produksi'];
                $content_kapasitas .= "
                                <li>
                                    <p>Untuk kapasitas produksi saat ini mencapai $realisasi_kapasitas $satuan untuk produksi $jenis foreach;</p>
                                </li>
                                ";
            }

            $content_csr = "";
            if ($data['is_csr']) {
                $content_csr .= "
                            <li>
                                <p>$nama_perusahaan memliki Program CSR {$data['program_csr']} dan sudah berjalan dan rutin kepada {$data['objek_csr']} dengan alokasi dana sebesar {$data['alokasi_dana_csr']};</p>
                            </li>
                            ";
            } else {
                $content_csr .= "
                            <li>
                                <p>$nama_perusahaan belum memliki Program CSR;</p>
                            </li>
                            ";
            }


            $content_kemitraan = "";
            if ($data['is_csr']) {
                $content_kemitraan .= "
                            <li>
                                <p>$nama_perusahaan telah bermitra;</p>
                            </li>
                            ";
            } else {
                $content_kemitraan .= "
                            <li>
                                <p>$nama_perusahaan belum bermitra dengan UMKM;</p>
                            </li>
                            ";
            }

            $rencana_investasi = 'Rp. ' . number_format($data['rencana_investasi']);
            $realisasi_investasi = 'Rp. ' . number_format($data['realisasi_investasi']);

            $summary = "
                        <p>Catatan (Koordinator)</p>
                        <p>A. Keterangan Perusahaan</p>
                            <ol>
                                <li>
                                    <p>$nama_perusahaan merupakan $status_perusahaan yang beralamat di $alamat $kabkota Jawa Tengah dan mempunyai Skala $skala_usaha;</p>
                                </li>
                                <li>
                                    <p>Pada saat pelaksaan pengawasan ke $nama_perusahaan, DPMPTSP Provinsi Jawa Tengah sudah berkoordinasi dan bertemu saat tiba dilokasi dengan Saudara $nama selaku $jabatan;</p>
                                </li>
                                <li>
                                <p>$nama_perusahaan mempunyai proyek usaha dengan skala resiko $resiko</p>
                                </li>
                            </ol>
                        <p>B. Berizinan</p>
                            <ol>
                                <li>
                                    <p>$nama_perusahaan mempunyai NIB dengan nomor: $nib Tanggal $tanggal_terbit_nib dengan KBLI ($kbli: $deskripsi_kbli);</p>
                                </li>
                                $content_ss
                                <li>
                                    <p>Pada status riil di lapangan, $nama_perusahaan $keterangan_riil.</p>
                                </li>
                            </ol>
                        <p>C. Investasi</p>
                            <ol>
                                <li>
                                    <p>Dari Nilai Rencana Investasi sebesar {$rencana_investasi} saat ini sudah terealisasi sebesar {$realisasi_investasi} ;</p>
                                </li>
                                $content_listrik
                                <li>
                                    <p>Perusahaan saat ini menempati lahan seluas {$data['luas_tanah']} m<sup>2 </sup>dengan luas bangunan {$data['luas_bangunan']} m<sup>2 </sup>dengan status {$data['status_tanah']};</p>
                                </li>
                                $content_lapor_lkpm
                                $content_tanggal_operasi
                                $content_tk
                            </ol>
                        <p>D. Kapasitas</p>
                            <ol>
                                $content_kapasitas
                                <li>
                                    <p>{$data['alur_produksi']}.</p>
                                </li>
                            </ol>
                        <p>E. Kewajiban</p>
                            <ol>
                                <li>
                                    <p>$nama_perusahaan sudah melaporkan LKPM Triwulan $tw dengan status {$data['status_lkpm']}. Terdapat realisasi investasi sebesar {$realisasi_investasi};</p>
                                </li>
                                $content_csr
                                $content_kemitraan
                            </ol>
                        ";

            $data['summary'] = $summary;
            $data['tanggal_bap'] = today();

            //Bap::create($data);

        }



        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
