<?php

namespace App\Filament\Resources\Cjip\ProyekInvestasiResource\Pages;

use App\Filament\Resources\Cjip\ProyekInvestasiResource;
use Filament\Actions;
use Filament\Actions\LocaleSwitcher;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Support\Facades\Auth;
use Filament\Notifications\Notification;

class EditProyekInvestasi extends EditRecord
{
    use EditRecord\Concerns\Translatable;

    protected static string $resource = ProyekInvestasiResource::class;

    protected function getHeaderActions(): array
    {
        return [
            LocaleSwitcher::make(),
            Actions\ViewAction::make(),
            Actions\DeleteAction::make(),
        ];
    }
    public static function getTranslatableLocales(): array
    {
        return ['id', 'en'];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        if (auth()->user()->hasRole('admin_cjip')) {
            $data['status'] = null;
        }
        return $data;
    }

    /*public function mount($record): void
    {
        $this->form->fill();
        parent::mount($record); // TODO: Change the autogenerated stub
    }*/

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }
    protected function getSavedNotification(): ?Notification
    {
        $name = Auth::user()->name;
        $recipient = auth()->user();
        return Notification::make()
            ->success()
            ->icon('heroicon-o-document-text')
            ->seconds(7)
            ->title('Saved By ' . $name)
            ->body('Proyek Investasi Edited Successfully.')
            ->sendToDatabase($recipient);
    }
}
